spring:
  docker:
    compose:
      lifecycle-management: start-only

  datasource:
    url: jdbc:postgresql://localhost:5432/moyeolak
    username: moyeolak
    password: moyeolak
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'Asia/Seoul'

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

google:
  api:
    key: ${GOOGLE_API_KEY}

odsay:
  api:
    key: ${ODSAY_API_KEY}

kakao:
  api:
    key: ${KAKAO_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, caches, prometheus
  endpoint:
    caches:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.cache: trace   # 캐시 히트/미스 로그
