CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE meeting (
    participant_count integer,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    meeting_id varchar(21) NOT NULL,
    PRIMARY KEY (meeting_id)
);

CREATE TABLE schedule_poll (
    end_time integer NOT NULL,
    start_time integer NOT NULL,
    confirmed_end_time timestamp(6),
    confirmed_start_time timestamp(6),
    created_at timestamp(6) NOT NULL,
    schedule_poll_id bigint GENERATED BY DEFAULT AS IDENTITY,
    updated_at timestamp(6) NOT NULL,
    meeting_id varchar(21) NOT NULL,
    poll_status varchar(255) NOT NULL,
    date_options varchar(1000) NOT NULL,
    PRIMARY KEY (schedule_poll_id)
);

CREATE TABLE location_poll (
    created_at timestamp(6) NOT NULL,
    location_poll_id bigint GENERATED BY DEFAULT AS IDENTITY,
    updated_at timestamp(6) NOT NULL,
    meeting_id varchar(21) NOT NULL,
    poll_status varchar(255) NOT NULL,
    PRIMARY KEY (location_poll_id)
);

CREATE TABLE participant (
    is_host boolean NOT NULL,
    created_at timestamp(6) NOT NULL,
    participant_id bigint GENERATED BY DEFAULT AS IDENTITY,
    updated_at timestamp(6) NOT NULL,
    meeting_id varchar(21) NOT NULL,
    local_storage_key varchar(255),
    name varchar(255) NOT NULL,
    PRIMARY KEY (participant_id)
);

CREATE TABLE schedule_vote (
    created_at timestamp(6) NOT NULL,
    participant_id bigint NOT NULL,
    schedule_poll_id bigint NOT NULL,
    schedule_vote_id bigint GENERATED BY DEFAULT AS IDENTITY,
    updated_at timestamp(6) NOT NULL,
    voted_date text NOT NULL,
    PRIMARY KEY (schedule_vote_id)
);

CREATE TABLE location_vote (
    departure_lat numeric(10, 7) NOT NULL,
    departure_lng numeric(10, 7) NOT NULL,
    created_at timestamp(6) NOT NULL,
    location_poll_id bigint NOT NULL,
    location_vote_id bigint GENERATED BY DEFAULT AS IDENTITY,
    participant_id bigint,
    updated_at timestamp(6) NOT NULL,
    departure_location varchar(255) NOT NULL,
    departure_name varchar(255),
    PRIMARY KEY (location_vote_id)
);

CREATE TABLE confirmed_location (
    confirmed_lat numeric(10, 7),
    confirmed_lng numeric(10, 7),
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_poll_id bigint,
    confirmed_location varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE nearby_place (
    base_latitude numeric(10, 7) NOT NULL,
    base_longitude numeric(10, 7) NOT NULL,
    distance_from_base integer,
    latitude numeric(10, 7),
    longitude numeric(10, 7),
    created_at timestamp(6) NOT NULL,
    nearby_place_id bigint GENERATED BY DEFAULT AS IDENTITY,
    updated_at timestamp(6) NOT NULL,
    provider_place_id varchar(300) NOT NULL,
    category varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    formatted_address varchar(500),
    kakao_place_url varchar(500),
    PRIMARY KEY (nearby_place_id)
);

CREATE TABLE nearby_place_hours (
    close_day integer NOT NULL,
    close_hour integer NOT NULL,
    close_minute integer NOT NULL,
    open_day integer NOT NULL,
    open_hour integer NOT NULL,
    open_minute integer NOT NULL,
    created_at timestamp(6) NOT NULL,
    nearby_place_hours_id bigint GENERATED BY DEFAULT AS IDENTITY,
    nearby_place_id bigint NOT NULL,
    updated_at timestamp(6) NOT NULL,
    PRIMARY KEY (nearby_place_hours_id)
);

CREATE TABLE stations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    line varchar(50),
    name varchar(100) NOT NULL,
    geom geometry(Point, 4326) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE location_poll
    ADD CONSTRAINT uk_location_poll_meeting UNIQUE (meeting_id);

ALTER TABLE schedule_poll
    ADD CONSTRAINT uk_schedule_poll_meeting UNIQUE (meeting_id);

ALTER TABLE participant
    ADD CONSTRAINT uk_participant_meeting_local_storage_key UNIQUE (meeting_id, local_storage_key);

ALTER TABLE nearby_place
    ADD CONSTRAINT uk_base_place UNIQUE (base_latitude, base_longitude, provider_place_id);

CREATE INDEX idx_base_coords ON nearby_place (base_latitude, base_longitude);

CREATE INDEX idx_stations_geom ON stations USING GIST (geom);

ALTER TABLE schedule_poll
    ADD CONSTRAINT fk_schedule_poll_meeting
    FOREIGN KEY (meeting_id) REFERENCES meeting (meeting_id);

ALTER TABLE location_poll
    ADD CONSTRAINT fk_location_poll_meeting
    FOREIGN KEY (meeting_id) REFERENCES meeting (meeting_id);

ALTER TABLE participant
    ADD CONSTRAINT fk_participant_meeting
    FOREIGN KEY (meeting_id) REFERENCES meeting (meeting_id);

ALTER TABLE schedule_vote
    ADD CONSTRAINT fk_schedule_vote_participant
    FOREIGN KEY (participant_id) REFERENCES participant (participant_id);

ALTER TABLE schedule_vote
    ADD CONSTRAINT fk_schedule_vote_schedule_poll
    FOREIGN KEY (schedule_poll_id) REFERENCES schedule_poll (schedule_poll_id);

ALTER TABLE location_vote
    ADD CONSTRAINT fk_location_vote_location_poll
    FOREIGN KEY (location_poll_id) REFERENCES location_poll (location_poll_id);

ALTER TABLE location_vote
    ADD CONSTRAINT fk_location_vote_participant
    FOREIGN KEY (participant_id) REFERENCES participant (participant_id);

ALTER TABLE confirmed_location
    ADD CONSTRAINT fk_confirmed_location_location_poll
    FOREIGN KEY (location_poll_id) REFERENCES location_poll (location_poll_id);

ALTER TABLE nearby_place_hours
    ADD CONSTRAINT fk_nearby_place_hours_nearby_place
    FOREIGN KEY (nearby_place_id) REFERENCES nearby_place (nearby_place_id);
