-- 외부 API 호출 통계 스냅샷: @Scheduled 잡이 주기적으로 MeterRegistry 누적값을 적재한다.
CREATE TABLE external_api_metric_snapshot (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captured_at          TIMESTAMP        NOT NULL,
    api                  VARCHAR(32)      NOT NULL,
    calls_total          BIGINT           NOT NULL,
    success_total        BIGINT           NOT NULL,
    failure_total        BIGINT           NOT NULL,
    rate_limited_total   BIGINT           NOT NULL,
    latency_p50_ms       DOUBLE PRECISION NOT NULL,
    latency_p95_ms       DOUBLE PRECISION NOT NULL,
    compute_routes_units BIGINT           NOT NULL DEFAULT 0,
    route_matrix_units   BIGINT           NOT NULL DEFAULT 0,
    error_breakdown      JSONB            NOT NULL DEFAULT '{}'
);

CREATE INDEX idx_external_api_metric_snapshot_api_captured
    ON external_api_metric_snapshot (api, captured_at);
